Traceback (most recent call last):
  File "C:\Users\46768458\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\46768458\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\46768458\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\46768458\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\46768458\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\46768458\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\46768458\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\46768458\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from textblob import Word
data['Story'] = data['Story'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
data['Story'].head()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [1;32mIn [17][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtextblob[39;00m [38;5;28;01mimport[39;00m Word
[0;32m      2[0m data[[38;5;124m'[39m[38;5;124mStory[39m[38;5;124m'[39m] [38;5;241m=[39m data[[38;5;124m'[39m[38;5;124mStory[39m[38;5;124m'[39m][38;5;241m.[39mapply([38;5;28;01mlambda[39;00m x: [38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m[38;5;241m.[39mjoin([Word(word)[38;5;241m.[39mlemmatize() [38;5;28;01mfor[39;00m word [38;5;129;01min[39;00m x[38;5;241m.[39msplit()]))
[0;32m      3[0m data[[38;5;124m'[39m[38;5;124mStory[39m[38;5;124m'[39m][38;5;241m.[39mhead()

[1;31mModuleNotFoundError[0m: No module named 'textblob'
ModuleNotFoundError: No module named 'textblob'

